name: Generate API Code

on:
  workflow_dispatch

permissions:
  contents: write
  pull-requests: write

jobs:
  generate:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Telepath
      uses: actions/checkout@v3
      with:
        path: telepath
        
    - name: Checkout Tellaptepab
      uses: actions/checkout@v3
      with:
        repository: telepath-php/tellaptepab
        path: tellaptepab
        
    - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
        
    - name: Install Dependencies
      run: |
        cd tellaptepab
        composer install --no-dev
        
    - name: Generate Code
      run: |
        cd tellaptepab
        php tellaptepab generate:methods --path=../telepath/src/
        php tellaptepab generate:types --path=../telepath/src/
        version=$(php tellaptepab info:version)
        echo "api_version=$version" >> $GITHUB_ENV
        echo "::notice::Latest Bot API Version detected: $version"
        
    - name: Commit Changes
      uses: peter-evans/create-pull-request@v4
      if: ${{ env.api_version }}
      with:
        path: telepath
        branch: "api-${{ env.api_version }}"
        commit-message: "Update code to detect latest changes to the API documentation"
        delete-branch: true
        title: "Bot API ${{ env.api_version }}"
        body: "Updated code to reflect the latest changes to the API documentation regarding API Version ${{ env.api_version }}"
        labels: "Bot API"
